[package]
name = "discord-wavenet"
version = "0.1.0"
authors = ["Sri Ramanujam <sricharan.ramanujam@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
songbird = { version = "0.2", features = ["builtin-queue"] }
serenity = { version = "0.10", features = ["cache", "standard_framework", "voice", "rustls_backend"]}
googapis = { version = "0.4", features = [ "google-cloud-texttospeech-v1" ] }
gouth = "0.1"
tonic = { version = "0.4", features = ["tls"] }
prost = "0.7"
prost-types = "0.7"
tokio = { version = "1", features = [ "full" ]}
anyhow = "1.0.40"
tracing-subscriber = "0.2.17"
tracing = "0.1.25"
tempfile = "3.2.0"
fastrand = "1.4.0"
tracing-futures = "0.2.5"

[dependencies.audiopus]
version = "0.3.0-rc.0"
