name: main

on:
  push:
    branches:
      - main
      - github-actions-revamp

jobs:
  build:
    strategy:
      matrix:
        target: ["x86_64-unknown-linux-gnu"]
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true
      -
        uses: Swatinem/rust-cache@v1.3.0
      -
        name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --target ${{ matrix.target }} --release
      -
        name: Set tag name in environment
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      -
        name: Set lowercase repository in environment
        run: echo "REPOSITORY_LOWERCASE=${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV
      -
        name: Debugging in prod
        run: ls -alh target/release/*
      -
        name: Create and push Docker image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          no-cache: true
          context: .
          tags: |
            ghcr.io/${{ env.REPOSITORY_LOWERCASE }}:${{ env.RELEASE_VERSION }}
